image:
  file: Dockerfile
ports:
- port: 8000
  onOpen: open-preview
- port: 3306
  onOpen: ignore
tasks:
- before: |
    php -r "file_exists('.env') || copy('.env.example', '.env');"
    url=$(gp url 8000); sed -i'' "s#^APP_URL=http://localhost*#APP_URL=$url\nASSET_URL=$url#g" .env  #change APP_URL and ASSET_URL to 8080 URL
  init: |
    composer install
  command: |
    php artisan key:generate --ansi
    php artisan serve
  - name: MySQL
    command: mysqld
  - name: Apache
    command: >
        apachectl start;
        multitail /var/log/apache2/error.log -I /var/log/apache2/access.log
